### ISSUE TITLE
Calls to the database are inefficient, and therefore page load is mind-numbingly slow.

### ISSUE THREAD

**Issue by AncientSwordRage** [AncientSwordRage/nWoD-db#11]
It might be that calls to the database are inefficient, not sure if it is due to the [N+1](http://stackoverflow.com/q/97197/1075247) or my over zealous use of link tables. 

But 4 seconds to get a JSON from a DB is wrong.

**Comment by rozza2058** [comment]
I don't know how much db work you've done before but try and make sure you
have indexes on as many tables as you can - it'll make link tables
infinitely more efficient.

**Comment by AncientSwordRage** [comment]
Ill look into it

**Comment by AncientSwordRage** [comment]
Ill look into it...though I'm not sure it's that big a problem.

![image](https://cloud.githubusercontent.com/assets/5961746/6481937/8d0d7020-c259-11e4-9d2e-a31bd92c43ad.png)

SQL query seems to take 3ms if Django Toolbar can be trusted. But the TTFB is the long call on the Mages.json. 

As for the angular download, I can only guess that's because I'm not using the CDN (?).

**Comment by rozza2058** [comment]
Wow, that's a lot of latency! 3.32s TTFB? Why's that happening? 7 seconds
to load angular.js? Do you have it local? Because that should be quicker
than CDN - is it minified?

**Comment by AncientSwordRage** [comment]
I thought it was a lot! It's local but not minified. I figured having it non-minfied was better for my education but I have not need it. Does minification add that much?

As for my TTFB is so monstrous, I have no idea.

**Comment by rozza2058** [comment]
It should barely add anything on a file by file basis. Good practice when
you have lots of files or large files, as it helps UX to have things load
quickly. Something about your system is weirdly slow and I don't know
enough about it to fix it for you - maybe it's Django?

**Comment by AncientSwordRage** [comment]
It's probably Django. Don't worry about fixing it for me though. It might be how it goes from  Django -> Rest Framework ->Json, and the reason the SQL is so light is as it's already loaded it, but the transform takes time?

Or it might just be my works network?

**Comment by AncientSwordRage** [comment]
It's a still a little slow to load the raw json from the api:

![image](https://cloud.githubusercontent.com/assets/5961746/6482508/86d7a810-c25e-11e4-96bf-a530fc760e32.png)

**Comment by AncientSwordRage** [comment]
Looking over my DB, I think I've massively over normalised the link between character and ability/skill/arcana.

I'm going to re-write the character models to keep the tables simple.
